<?php 

define("ERROR_LOGIN_ALREADY_EXISTS", 1);
define("ERROR_DB_NAME_UNKNOWN", 2);
define("ERROR_FILL_BOTH_FIELDS", 3);
define("ERROR_CLIENT_DOES_NOT_EXIST", 4);
define("ERROR_WRONG_PASSWORD", 5);

?>